# Setup
title:        APPMOBTEAM2014 OFFICIALPAGE
tagline:      Haii Welcome , Ini adalah Sebuah halaman yang berisi tentang mata kuliah Aplication Mobile Sebagai Tugas Akhir dari dosen Kami Mr.Jazman , Halaman ini di design oleh Theo Luckita Milala,Satria Salam,Helfa Safitri Jurusan SISTEM INFORMASI angkatan 2014 mata kuliah Aplication Mobile kelas A 2015/2016 , Enjooyy...
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Copyright © 2016 Theo Luckita Milala,Satria Salam,Helfa Safitri. All Rights Reserved.
  url:        https://appmobteam2014.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
