# Setup
title:        APPMOBTEAM2014 OFFICIALPAGE
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Copyright © 2016 Theo Luckita Milala,Satria Salam,Helfa Safitri. All Rights Reserved.
  url:        https://appmobteam2014.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
